"""apply_patch — multi-hunk, multi-file unified-diff application, all-or-nothing.

Every diff fixture below was generated by real `git diff` against a real git
repo, not hand-typed, so the parser is proven against authentic hunk syntax —
including the parts easy to get subtly wrong (multi-hunk line-number tracking,
`/dev/null` new-file and deletion markers) — not a guess at the format.

``Workspace.apply_patch`` returns ``"error: ..."`` strings on failure, matching
``write``/``edit``'s own convention (never raises) — tests assert on that
prefix, not on a caught exception.
"""

from __future__ import annotations

from harness.workspace import Workspace

MULTI_HUNK = """\
diff --git a/multi.txt b/multi.txt
index 19339a3..24512df 100644
--- a/multi.txt
+++ b/multi.txt
@@ -1,6 +1,6 @@
 line1
 line2
-line3
+line3-CHANGED
 line4
 line5
 line6
@@ -22,7 +22,7 @@ line21
 line22
 line23
 line24
-line25
+line25-CHANGED
 line26
 line27
 line28
"""

NEW_FILE = """\
diff --git a/newfile.txt b/newfile.txt
new file mode 100644
index 0000000..2809c55
--- /dev/null
+++ b/newfile.txt
@@ -0,0 +1,2 @@
+brand new content
+second line
"""

DELETED_FILE = """\
diff --git a/gone.txt b/gone.txt
deleted file mode 100644
index cefda99..0000000
--- a/gone.txt
+++ /dev/null
@@ -1 +0,0 @@
-to be removed
"""


def _seeded_multi(tmp_path):
    lines = "\n".join(f"line{i}" for i in range(1, 31)) + "\n"
    (tmp_path / "multi.txt").write_text(lines)
    return Workspace(root=tmp_path)


def test_multi_hunk_applies_both_hunks_in_one_file(tmp_path):
    ws = _seeded_multi(tmp_path)
    result = ws.apply_patch(MULTI_HUNK)
    assert not result.startswith("error"), result
    lines = (tmp_path / "multi.txt").read_text().splitlines()
    assert lines[2] == "line3-CHANGED"
    assert lines[24] == "line25-CHANGED"
    # every OTHER line is untouched — a hunk must not bleed into its neighbors
    assert lines[0] == "line1" and lines[1] == "line2" and lines[3] == "line4"
    assert lines[23] == "line24" and lines[25] == "line26"
    assert len(lines) == 30


def test_new_file_creation(tmp_path):
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(NEW_FILE)
    assert not result.startswith("error"), result
    assert (tmp_path / "newfile.txt").read_text() == "brand new content\nsecond line\n"


def test_new_file_creation_refuses_to_overwrite_an_existing_file(tmp_path):
    (tmp_path / "newfile.txt").write_text("already here\n")
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(NEW_FILE)
    assert result.startswith("error"), result
    assert "newfile.txt" in result
    assert (tmp_path / "newfile.txt").read_text() == "already here\n", "must not have been touched"


def test_file_deletion(tmp_path):
    (tmp_path / "gone.txt").write_text("to be removed\n")
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(DELETED_FILE)
    assert not result.startswith("error"), result
    assert not (tmp_path / "gone.txt").exists()


def test_deletion_refuses_when_current_content_does_not_match(tmp_path):
    (tmp_path / "gone.txt").write_text("something else entirely\n")
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(DELETED_FILE)
    assert result.startswith("error"), result
    assert (tmp_path / "gone.txt").exists(), "must not have deleted a file whose content diverged"


def test_context_mismatch_is_rejected_not_guessed(tmp_path):
    """A hunk's context must match EXACTLY at the claimed location — no fuzzy/bounded
    search fallback. Real patch tools "fuzz" a nearby match; that is exactly the kind
    of guessing carbon's edit_file_tool already refuses (unique-match-or-reject)."""
    lines = "\n".join(f"DRIFTED{i}" for i in range(1, 31)) + "\n"
    (tmp_path / "multi.txt").write_text(lines)  # content has drifted from what MULTI_HUNK expects
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(MULTI_HUNK)
    assert result.startswith("error"), result
    assert "multi.txt" in result
    # nothing written — the file is byte-for-byte what it was
    assert (tmp_path / "multi.txt").read_text() == lines


def test_atomicity_across_files_one_bad_hunk_blocks_every_write(tmp_path):
    """A patch touching two files where only the SECOND file's content has drifted:
    the first file's hunk would apply cleanly in isolation, but the whole patch must
    still be all-or-nothing — the first file must be untouched too."""
    good_lines = "\n".join(f"line{i}" for i in range(1, 31)) + "\n"
    (tmp_path / "multi.txt").write_text(good_lines)
    (tmp_path / "gone.txt").write_text("drifted, does not match the deletion hunk\n")
    combined = MULTI_HUNK + DELETED_FILE
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch(combined)
    assert result.startswith("error"), result
    assert (tmp_path / "multi.txt").read_text() == good_lines, (
        "the FIRST file's valid hunk must not have been committed once the SECOND failed"
    )
    assert (tmp_path / "gone.txt").exists()


def test_multi_file_patch_applies_all_files_together(tmp_path):
    good_lines = "\n".join(f"line{i}" for i in range(1, 31)) + "\n"
    (tmp_path / "multi.txt").write_text(good_lines)
    ws = Workspace(root=tmp_path)
    combined = MULTI_HUNK + NEW_FILE
    result = ws.apply_patch(combined)
    assert not result.startswith("error"), result
    assert (tmp_path / "multi.txt").read_text().splitlines()[2] == "line3-CHANGED"
    assert (tmp_path / "newfile.txt").read_text() == "brand new content\nsecond line\n"


def test_path_traversal_is_refused(tmp_path):
    ws = Workspace(root=tmp_path)
    escaping = NEW_FILE.replace("newfile.txt", "../escaped.txt")
    result = ws.apply_patch(escaping)
    assert result.startswith("error"), result
    assert not (tmp_path.parent / "escaped.txt").exists()


def test_empty_patch_is_a_clean_no_op(tmp_path):
    ws = Workspace(root=tmp_path)
    result = ws.apply_patch("")
    assert not result.startswith("error")
    assert "no changes" in result.lower()


def test_returns_a_summary_naming_the_touched_files(tmp_path):
    ws = _seeded_multi(tmp_path)
    result = ws.apply_patch(MULTI_HUNK)
    assert "multi.txt" in result


def test_malformed_hunk_header_is_refused_cleanly(tmp_path):
    ws = _seeded_multi(tmp_path)
    broken = MULTI_HUNK.replace("@@ -1,6 +1,6 @@", "@@ garbage @@")
    result = ws.apply_patch(broken)
    assert result.startswith("error"), result
